name: gasjm
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  dio: null
  equatable: ^2.0.3
  #Depenencias para Firebase
  firebase_auth: ^2.0.0
  firebase_core: ^1.4.0
  cloud_firestore: ^1.0.7
  firebase_database: ^7.2.2
  firebase_storage: ^8.0.1
  flutter_facebook_auth: ^4.0.1
  google_sign_in: ^5.0.3

  firebase_dynamic_links: ^2.0.0
  #otros
  fluttertoast: ^8.0.6
  #datos en local
  shared_preferences: ^2.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_card_swipper: ^0.4.0
  flutter_clean_calendar: ^1.1.0
  flutter_secure_storage: ^4.2.0
  flutter_spinkit: null
  flutter_svg: ^0.22.0
  get: ^4.1.4
  #maps gps
  geolocator: ^7.1.0
  google_maps_flutter: ^2.0.6
  #
  geocoding: ^2.0.1
  #ubicacion actual
  location: ^4.3.0
  

  #formatos
  intl: null
  #permisos
  permission_handler: ^8.1.6
  pod: ^0.14.0
  provider: ^6.0.0
  rating_dialog: ^2.0.1
  #calendario
  syncfusion_flutter_calendar: ^19.1.54
  #idioma para fecha
   
  #fechas
  #flutter_material_pickers: ^3.1.0

dev_dependencies:
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
